### PR TITLE
NEW: logback config parameter appendStackTraceToFullMessage

### PR DESCRIPTION
**Pull request by VittorioZinno**
Make sure that:

- [ ] You have read the [contribution guidelines](https://github.com/mp911de/logstash-gelf/blob/master/.github/CONTRIBUTING.md).
- [ ] You use the code formatters provided [here](https://github.com/mp911de/logstash-gelf/blob/master/as7formatter.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.

 

Hi Mark

I've tried my best to be a worthy contributor. The grayLog server provided in our environment indexes the default field full_message. We used before this logback gelf appender [https://github.com/osiegmar/logback-gelf](url) which appendes the whole StackTrace to the full_message. I perfer your logback gelf appender implementation, so I'm trying to pull request this as a feature. I've introduced a logback appender parameter `<appendStackTraceToFullMessage>true</appendStackTraceToFullMessage>` to enable this behaviour.
I did my best to cover the change by a unit test. (I've extended a very simple existing unit test).
By the way I'm struggling running the existing tests in my environment (eclipse oxygen, JUnit5 plugin). Hope you consider my pull request, or maybe you have a better idea for the feature.

This is the Unit Test Report of your master branch hacking pom for missing artifact 
```
<dependency>
	<groupId>xerces</groupId>
	<artifactId>xercesImpl</artifactId>
	<scope>test</scope>
	<version>2.9.1</version>
</dependency>
```
unittestreport

Missing artifact, do you have any idea?
missing

### CODE REVIEW

**Comment by VittorioZinno** [comment]
By the way, I've used your Java Code AS7. I don't know why there are white space and line seprator diffs

**Comment by mp911de** [comment]
Thanks for your pull request. Please always file a ticket before submitting a pull request. logstash-gelf stores the stack trace in a separate field to maintain separation of concerns and to not mix things. Adding such functionality increases complexity in this library and can be solved differently.

Pre-processing GELF messages (using e.g. logstash for further transformation) is the way better approach. You can transform log events with such tools to the format you want to have it in. Adding tweaks and quirks to log appenders for individual customizations is not the right way to go. Otherwise, the library would end up with a ton of flags which no one would really understand what the individual flags really do.

Looking at the changes: If a formatter does not work for you or produces a totally different style than you see in a repository, it's better to leave the files unformatted. The change for [`pom.xml`](https://github.com/mp911de/logstash-gelf/pull/119/files#diff-600376dffeb79835ede4a0b285078036) removes and re-adds all lines so it's no longer obvious what was changed. Same for the removal of trailing whitespaces.

**Comment by VittorioZinno** [comment]
Thanks a lot for your reply. You were super sonic fast.

I understand you point rejecting my pull request. I was influenced from
this appender https://github.com/osiegmar/logback-gelf which uses logback
layouting to format the messages.

I will follow up your proposal by pre-processing.

In your CONTRIBUTING.md creating a ticket before pull requesting is not
mentioned. Do I miss a github convetion?

About the white spaces, you're absolutely right it was my mistake. I asumed
that you would to anyway cherry picking and not considering pom.xml.
Although I was using your as7formatter.xml
<https://github.com/mp911de/logstash-gelf/blob/master/as7formatter.xml> my
IDE used tabs instead of whitespaces.

live long and prosper

**Comment by mp911de** [comment]
No worries, you didn't miss anything. It's just that you spent some effort in learning how logstash-gelf works and you have built some code which isn't merged now. Creating a ticket and asking/discussing your requirements would not require any coding for you to figure out that your feature isn't something that would be implemented in this library.

Closing this pull request as it's not going to be merged here.

**Comment by VittorioZinno** [comment]
Hihi, forking and implementing was the glorious idea of my boss. Hihi.

Again you're absolutely right, asking would have been the better aproach
and so others could have got advantages of that conversation. For the next
few days we have a temporary solution until I get it done properly.

Have a great week-end.

**Comment by mp911de** [comment]
Keep up contributing to open source for a vibrant community, have a great time, too.

**Pull request closed without merging**
