### PR TITLE
Fixes #170: WildFlyGelfLogHandler does not honor "enabled" attribute …

### LINKED ISSUE #170: WildFlyGelfLogHandler does not honor "enabled" attribute of <custom-handler>
Testcase
* Install the wildfly module as described in the readme: https://github.com/mp911de/logstash-gelf#wildfly
* Configure standalone.xml (wildfly version does not seem to matter):
```xml
<custom-handler name="Some-Graylog"
                            class="biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler"
                            module="biz.paluch.logging"
                            enabled="false">
  <level name="INFO" />
  <!-- other settings do not matter -->
</custom-handler>
```

Even though the attribute "enabled" is set to "false", I see logs if there's nothing listening on localhost:12201:
LogManager error of type GENERIC_FAILURE: Connection refused
java.io.IOException: Cannot send data to localhost:12200

A first glance into the WildFlyGelfLogHandler.java Source does not show anything about reading the "enabled" attribute

Full Error stack:

```
19:23:56,490 INFO  [org.jboss.as.connector] (MSC service thread 1-5) WFLYJCA0009: Starting JCA Subsystem (WildFly/IronJacamar 1.4.6.Final)
LogManager error of type GENERIC_FAILURE: Connection refused
java.io.IOException: Cannot send data to localhost:12200
	at biz.paluch.logging.gelf.intern.sender.GelfTCPSender.sendMessage(GelfTCPSender.java:126)
	at biz.paluch.logging.gelf.jul.GelfLogHandler.publish(GelfLogHandler.java:134)
	at biz.paluch.logging.gelf.wildfly.WildFlyGelfLogHandler.publish(WildFlyGelfLogHandler.java:83)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:314)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
	at org.jboss.logmanager.LoggerNode.publish(LoggerNode.java:322)
	at org.jboss.logmanager.Logger.logRaw(Logger.java:850)
	at org.jboss.logmanager.Logger.log(Logger.java:802)
	at org.jboss.logging.JBossLogManagerLogger.doLogf(JBossLogManagerLogger.java:53)
	at org.jboss.logging.Logger.logf(Logger.java:2398)
	at org.jboss.as.jaxrs.logging.JaxrsLogger_$logger.resteasyVersion(JaxrsLogger_$logger.java:129)
	at org.jboss.as.jaxrs.JaxrsSubsystemAdd.performBoottime(JaxrsSubsystemAdd.java:60)
	at org.jboss.as.controller.AbstractBoottimeAddStepHandler.performRuntime(AbstractBoottimeAddStepHandler.java:116)
	at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:151)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:980)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:726)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:450)
	at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:386)
19:23:56,427 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 35) WFLYIO001: Worker 'default' has auto-configured to 8 core threads with 64 task threads based on your 4 available processors
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
19:23:56,480 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 49) WFLYSEC0002: Activating Security Subsystem
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at biz.paluch.logging.gelf.intern.sender.GelfTCPSender.connect(GelfTCPSender.java:164)
	at biz.paluch.logging.gelf.intern.sender.GelfTCPSender.sendMessage(GelfTCPSender.java:103)
	... 23 more
```

### PR DESCRIPTION
**Pull request by HonoluluHenk**
See title

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks a lot for the fix. Care to simplify the test in the sense of using a unit test? Another integration test is quite heavyweight.

**Comment by HonoluluHenk** [comment]
I implemented the unit test and added some docs.

But here's some food for thought:
The setEnabled() method is not part of any interface and is just called by wildfly convention. I did only find that convention by trial and error as I could not find any docs about implementing a <custom-handler>.
If anybody decides to remove that setEnabled() method "because it is only used in unit tests", disabling the logger will be broken.
Only an integration test in a real wildfly environment will show this regression.

But development/test cycle speed is also an issue I can relate to...

If you still want that integration test to be removed, I'll be glad to comply but I had to mention the risks.

**Comment by mp911de** [comment]
Thanks a lot. Removing `public` methods is a bad habit and should not happen on released API. Almost all `public` methods on our appenders/handlers have no further interface binding but stick to the Java Bean Properties contract.

**Comment by mp911de** [comment]
That's merged now.

**Pull request closed without merging**
