### PR TITLE
Adding Authentication header to Http sender when user info is supplied.

### PR DESCRIPTION
**Pull request by chka73**
Leveraging an earlier PR by using java8 base64 encoding the user info part of a URL with basic auth credentials given.

### CODE REVIEW

**Comment by mp911de** [comment]
Thanks for your pull request. We should remain Java 1.6-compatible and not upgrade the required Java version just because of a single class that seems useful for HTTP authentication.

**Comment by chka73** [comment]
Ok
Easier to solve using an external lib or java8 native lib than to implement base64 on our own though.
Will use this version in our projects then. 
Thanks.

**Comment by chka73** [comment]
Just one question, why do you want to maintain compatibility to java6? It's been end of support for a while now, time to move forward perhaps?

**Comment by mp911de** [comment]
True from a standpoint of Java 12 and if you look from a greenfield perspective. There are still tons of applications in production that range from Java 1.3 (!!) to Java 1.8. Various vendors keep these alive with Java 6 support contracts or people run applications without upgrading the Java runtime. 

As long as we don’t have a compelling reason to upgrade to Java 8, I don’t see a reason to „take away“ this library from our users. 

We could think the same way about log4j 1.2 and yet we get from time to time feature requests and bug reports in these constellations. 

Using newer features, like built-in base64 or switching to diamond syntax, lambdas, etc. seem nice for the maintenance but this causes some pain for users and we should always consider our benefit vs. the cost for users. 

Sorry if that sounds like a rant, I wanted mostly explain my way of thinking here.

**Comment by rjayasinghe** [comment]
Take SAP. They have their own commercial JDK distro with support contracts up to 20 years.

Well done Mark!

**Comment by chka73** [comment]
I get the argument.
We need the upgrade though so will use my fork of it. 
And I agree on the praise, the lib works very well. Thanks!

**Pull request closed without merging**
